/**
 * Created by 弘树<tiehang.lth@alibaba-inc.com> on 14/12/24.
 * 压缩JS
 */
module.exports = {
	options: {
		banner: '/*! Generated by Clam: <%= abcpkg.name %> */\n',
		beautify: {
			ascii_only: true
		}
	},
	main: {
		files: [
			{
				expand: true,
				cwd: 'src/',
				src: ['config.js'],
				dest: 'build/',
				ext: '-min.js'
			}
		]
	},
	offline: {
		files: [
			{
				expand: true,
				cwd: 'build_offline/',
				src: ['**/*_combo.js'],
				dest: 'build_offline/'
			}
		]
	}
};